trigger:
- master

pool:
  vmImage: 'windows-latest'

variables: 
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/CrowdedPrison.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/CrowdedPrison.Wpf.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory) --configuration $(buildConfiguration)'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: CrowdedPrison
  